/*! Copyright (c) 2020, XAPPmedia */
export * from "./isActionable";
export * from "./isActiveWithin";
export * from "./isCompilablePath";
export * from "./isExecutablePath";
export * from "./isFirstTime";
export * from "./isGlobalHandler";
export * from "./isHandler";
export * from "./isHaveNotSeenWithin";
export * from "./isHistoricalPath";
export * from "./isIntent";
export * from "./isLastActive";
export * from "./isLastActiveResponse";
export * from "./isLinkoutSuggestion";
export * from "./isPreviousHandlerPath";
export * from "./isSchedulableResponse";
export * from "./isScheduled";
export * from "./isTemplatedList";
export * from "./isTimeContextual";